### ISSUE TITLE
Duration and relativedelta

### ISSUE THREAD

**Issue by scls19fr** [OldhamMade/PySO8601#10]
Hello,

`PySO860.parse_duration` should be able to return a `dateutil.relativedelta.relativedelta` from a duration ISO 8601 string (because years don't have always 365 days and months 30 days)
see also https://bugs.launchpad.net/dateutil/+bug/1507735

Kind regards

**Comment by scls19fr** [comment]
If you don't want to use `dateutil` an other approach could be to use Pandas `DateOffset` like

    pd.tseries.offsets.DateOffset(years=2, months=6, days=1)

**Comment by OldhamMade** [comment]
Accurate durations is something I'd like to support, but it's rather tricky. If you're provided with `P3M10D` and no point of reference, you can't really provide an accurate calculation. 3 months and 10 days would be different if it were Jan-Mar compared to Oct-Dec, without taking in to consideration leap years.

`dateutil.relativedelta.relativedelta` will only work if you have both a start and end datetime, which in this case we don't have. I believe it's the same for `DateOffset` in pandas.

I do have an issue open (#3) to work on durations which have a datetime provided. I'll bump the priority on it.

**Comment by OldhamMade** [comment]
Fixed in version `0.2.0`
